openapi: 3.0.2
info:
  title: Tilitintin API
  description: Complete set of API end-points to manage bookkeeping.
  version: '1.0'
  contact:
    name: Tommi Ronkainen
  license:
    name: GPL-3.0
    url: https://opensource.org/licenses/GPL-3.0

servers:
  - url: http://localhost:3101
    description: Local development host

paths:
  /auth:
    $ref: paths/auth.yaml

  /db:
    $ref: paths/db.yaml

  /db/{databaseName}:
    parameters:
      - in: path
        name: databaseName
        schema:
          type: string
          pattern:  ^[0-9a-z-_]+$
        required: true
        description: Name of the database.
    $ref: paths/db/id.yaml

  /db/upload:
    $ref: paths/db/upload.yaml

  /db/{databaseName}/account:
    parameters:
    - in: path
      name: databaseName
      schema:
        type: string
        pattern: ^[0-9a-z-_]+$
      required: true
      description: Name of the database.
    $ref: paths/account.yaml

  /db/{databaseName}/account/{id}:
    parameters:
    - in: path
      name: databaseName
      schema:
        type: string
        pattern:  ^[0-9a-z-_]+$
      required: true
      description: Name of the database.
    - in: path
      name: id
      schema:
        type: integer
        minimum: 1
      required: true
      description: The ID of the account.
    $ref: paths/account/id.yaml
