openapi: 3.0.2
info:
  title: Tilitintin API
  description: Complete set of API end-points to manage bookkeeping.
  version: '1.0'
  contact:
    name: Tommi Ronkainen
  license:
    name: GPL-3.0
    url: https://opensource.org/licenses/GPL-3.0
servers:
  - url: http://localhost:3101
    description: Local development host
paths:
  /db:
    $ref: paths/db.yaml
  /db/{name}:
    $ref: paths/db/id.yaml
  /db/upload:
    $ref: paths/db/upload.yaml
