version: '2'

services:

  backend:
    container_name: tilitintin-backend
    build:
      context: backend
    ports:
      - 3101:3101
    volumes:
      - ./backend/databases:/var/app/databases

  ui:
    container_name: tilitintin-ui
    build:
      context: ui
    ports:
      - 3102:3102
    environment:
      PORT: 3102
